# Use an official Node.js runtime as a base image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --only=production

# Bundle app source
COPY . .

# Expose the port
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "start"]